// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlSpqtBFn0hw4HyYII8e-Fl5tHs0evMxo',
    appId: '1:98440205225:web:8f264921e44ae820456ab8',
    messagingSenderId: '98440205225',
    projectId: 'mob1-f4b1e',
    authDomain: 'mob1-f4b1e.firebaseapp.com',
    storageBucket: 'mob1-f4b1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Oct4Y4NTAbVWnreiaKG2C4BjkQQ54wk',
    appId: '1:98440205225:android:35ba9e11def42653456ab8',
    messagingSenderId: '98440205225',
    projectId: 'mob1-f4b1e',
    storageBucket: 'mob1-f4b1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDityMsdJ7VZJksA225qMBZEU--mudEzRg',
    appId: '1:98440205225:ios:bb6a7f6482fbc9b9456ab8',
    messagingSenderId: '98440205225',
    projectId: 'mob1-f4b1e',
    storageBucket: 'mob1-f4b1e.firebasestorage.app',
    iosBundleId: 'com.example.mobileDevProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDityMsdJ7VZJksA225qMBZEU--mudEzRg',
    appId: '1:98440205225:ios:bb6a7f6482fbc9b9456ab8',
    messagingSenderId: '98440205225',
    projectId: 'mob1-f4b1e',
    storageBucket: 'mob1-f4b1e.firebasestorage.app',
    iosBundleId: 'com.example.mobileDevProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlSpqtBFn0hw4HyYII8e-Fl5tHs0evMxo',
    appId: '1:98440205225:web:4ec108b78a0f8fa1456ab8',
    messagingSenderId: '98440205225',
    projectId: 'mob1-f4b1e',
    authDomain: 'mob1-f4b1e.firebaseapp.com',
    storageBucket: 'mob1-f4b1e.firebasestorage.app',
  );
}
